"""Built-in skill metadata. Bodies stay in small markdown files and load only when selected."""

SKILL_VERSION = 6

_BUILTINS = {
    "static_web": {"file": "static_web.md", "max_chars": 2200, "priority": 90},
    "visual_design": {"file": "visual_design.md", "max_chars": 2600, "priority": 100},
    "photography_portfolio": {"file": "photography_portfolio.md", "max_chars": 3200, "priority": 140},
    "responsive_web": {"file": "responsive_web.md", "max_chars": 1800, "priority": 80},
    "frontend_quality_baseline": {"file": "frontend_quality_baseline.md", "max_chars": 2200, "priority": 95},
    "visual_qa": {"file": "visual_qa.md", "max_chars": 3000, "priority": 135},
    "asset_sourcing": {"file": "asset_sourcing.md", "max_chars": 2400, "priority": 120},
    "typography_image_strategy": {"file": "typography_image_strategy.md", "max_chars": 2200, "priority": 92},
    "saas_landing": {"file": "saas_landing.md", "max_chars": 2400, "priority": 115},
    "restaurant_hospitality": {"file": "restaurant_hospitality.md", "max_chars": 2400, "priority": 115},
    "ecommerce_storefront": {"file": "ecommerce_storefront.md", "max_chars": 2400, "priority": 115},
    "agency_portfolio": {"file": "agency_portfolio.md", "max_chars": 2400, "priority": 115},
    "real_estate": {"file": "real_estate.md", "max_chars": 2400, "priority": 115},
    "personal_portfolio": {"file": "personal_portfolio.md", "max_chars": 2400, "priority": 115},
    "composition_mastery": {"file": "composition_mastery.md", "max_chars": 3000, "priority": 132},
    "typography_mastery": {"file": "typography_mastery.md", "max_chars": 2800, "priority": 130},
    "image_art_direction": {"file": "image_art_direction.md", "max_chars": 2800, "priority": 131},
    "portfolio_curation": {"file": "portfolio_curation.md", "max_chars": 2600, "priority": 128},
    "content_integrity": {"file": "content_integrity.md", "max_chars": 2600, "priority": 122},
    "conversion_journey": {"file": "conversion_journey.md", "max_chars": 2400, "priority": 112},
    "accessibility_mastery": {"file": "accessibility_mastery.md", "max_chars": 2600, "priority": 108},
    "interaction_polish": {"file": "interaction_polish.md", "max_chars": 2200, "priority": 88},
    "information_architecture": {"file": "information_architecture.md", "max_chars": 2400, "priority": 110},
    "forms_booking": {"file": "forms_booking.md", "max_chars": 2400, "priority": 106},
    "performance_web": {"file": "performance_web.md", "max_chars": 2200, "priority": 98},
    "luxury_branding": {"file": "luxury_branding.md", "max_chars": 2400, "priority": 116},
    "debugging_mastery": {"file": "debugging_mastery.md", "max_chars": 2600, "priority": 135},
    "testing_mastery": {"file": "testing_mastery.md", "max_chars": 2600, "priority": 125},
    "python_mastery": {"file": "python_mastery.md", "max_chars": 2600, "priority": 120},
    "javascript_typescript_mastery": {"file": "javascript_typescript_mastery.md", "max_chars": 2600, "priority": 120},
    "backend_api_mastery": {"file": "backend_api_mastery.md", "max_chars": 2800, "priority": 125},
    "database_mastery": {"file": "database_mastery.md", "max_chars": 2600, "priority": 120},
    "security_mastery": {"file": "security_mastery.md", "max_chars": 2600, "priority": 128},
    "performance_engineering": {"file": "performance_engineering.md", "max_chars": 2400, "priority": 118},
    "refactoring_mastery": {"file": "refactoring_mastery.md", "max_chars": 2400, "priority": 116},
    "deployment_mastery": {"file": "deployment_mastery.md", "max_chars": 2600, "priority": 122},
    "frontend_architecture": {"file": "frontend_architecture.md", "max_chars": 2600, "priority": 118},
    "code_review_mastery": {"file": "code_review_mastery.md", "max_chars": 2600, "priority": 124},
    "llm_engineering": {"file": "llm_engineering.md", "max_chars": 2800, "priority": 145},
    "agent_systems": {"file": "agent_systems.md", "max_chars": 2800, "priority": 148},
    "rag_mastery": {"file": "rag_mastery.md", "max_chars": 2800, "priority": 142},
    "ai_evaluation": {"file": "ai_evaluation.md", "max_chars": 2600, "priority": 132},
    "prompt_context_engineering": {"file": "prompt_context_engineering.md", "max_chars": 2600, "priority": 136},
    "ml_engineering": {"file": "ml_engineering.md", "max_chars": 2800, "priority": 138},
    "data_engineering": {"file": "data_engineering.md", "max_chars": 2800, "priority": 132},
    "vector_search": {"file": "vector_search.md", "max_chars": 2600, "priority": 128},
    "multimodal_ai": {"file": "multimodal_ai.md", "max_chars": 2600, "priority": 130},
    "saas_architecture": {"file": "saas_architecture.md", "max_chars": 2800, "priority": 138},
    "multi_tenant_systems": {"file": "multi_tenant_systems.md", "max_chars": 2600, "priority": 136},
    "payments_billing": {"file": "payments_billing.md", "max_chars": 2800, "priority": 136},
    "auth_identity": {"file": "auth_identity.md", "max_chars": 2800, "priority": 138},
    "mobile_app_mastery": {"file": "mobile_app_mastery.md", "max_chars": 2800, "priority": 134},
    "desktop_app_mastery": {"file": "desktop_app_mastery.md", "max_chars": 2600, "priority": 128},
    "distributed_systems": {"file": "distributed_systems.md", "max_chars": 2800, "priority": 138},
    "event_driven_systems": {"file": "event_driven_systems.md", "max_chars": 2600, "priority": 130},
    "realtime_systems": {"file": "realtime_systems.md", "max_chars": 2600, "priority": 132},
    "cloud_architecture": {"file": "cloud_architecture.md", "max_chars": 2800, "priority": 132},
    "devops_ci_cd": {"file": "devops_ci_cd.md", "max_chars": 2600, "priority": 126},
    "observability_mastery": {"file": "observability_mastery.md", "max_chars": 2600, "priority": 126},
    "reliability_sre": {"file": "reliability_sre.md", "max_chars": 2800, "priority": 132},
    "robotics_systems": {"file": "robotics_systems.md", "max_chars": 3000, "priority": 150},
    "embedded_iot": {"file": "embedded_iot.md", "max_chars": 2800, "priority": 142},
    "control_systems": {"file": "control_systems.md", "max_chars": 2800, "priority": 146},
    "product_architecture": {"file": "product_architecture.md", "max_chars": 2800, "priority": 130},
    "product_ux": {"file": "product_ux.md", "max_chars": 2600, "priority": 122},
    "cli_tooling": {"file": "cli_tooling.md", "max_chars": 2400, "priority": 120},
    "sdk_library_design": {"file": "sdk_library_design.md", "max_chars": 2600, "priority": 124},
    "api_integration_mastery": {"file": "api_integration_mastery.md", "max_chars": 2600, "priority": 128},
    "search_recommendation": {"file": "search_recommendation.md", "max_chars": 2800, "priority": 130},
    "computer_vision": {"file": "computer_vision.md", "max_chars": 2800, "priority": 136},
    "systems_programming": {"file": "systems_programming.md", "max_chars": 2800, "priority": 130},
    "go_services": {"file": "go_services.md", "max_chars": 2600, "priority": 126},
    "jvm_kotlin_mastery": {"file": "jvm_kotlin_mastery.md", "max_chars": 2600, "priority": 126},
    "dotnet_mastery": {"file": "dotnet_mastery.md", "max_chars": 2600, "priority": 126},
    "game_simulation": {"file": "game_simulation.md", "max_chars": 2800, "priority": 132},
}

def builtin_registry():
    return {name: dict(meta, id=name, source="builtin") for name, meta in _BUILTINS.items()}
